# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # tests:
  #   runs-on: ubuntu-18.04
  #   timeout-minutes: 10

  #   env:
  #     CI: false

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.15.1

  #     - name: Install Dependencies
  #       run: |
  #         yarn install

  #     - name: Test
  #       run: |
  #         yarn test
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master'

    env:
      API_HOST: ${{ secrets.API_HOST }}
      CI: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build


