# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # tests:
  #   runs-on: ubuntu-18.04
  #   timeout-minutes: 10

  #   env:
  #     CI: false

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 14.15.1

  #     - name: Install Dependencies
  #       run: |
  #         yarn install

  #     - name: Test
  #       run: |
  #         yarn test
  deploy:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    if: github.ref == 'refs/heads/master'

    env:
      SSH_HOST: ${{ secrets.SSH_HOST}}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      BUILD_ROOT_PATH: ${{ secrets.BUILD_ROOT_PATH }}
      CI: false
      REACT_APP_API_HOST: ${{ secrets.API_HOST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.1

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build
      
      - name: Copy ssh key
        run: |
          echo "$SSH_KEY" > secret_key
          chmod 600 secret_key

      - name: Deploy files builded
        run: |
          scp -o StrictHostKeyChecking=no -P $SSH_PORT -i secret_key -r build/* $SSH_USER@$SSH_HOST:$BUILD_ROOT_PATH/
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT -i secret_key $SSH_USER@$SSH_HOST \cp -f $BUILD_ROOT_PATH/index.html $BUILD_ROOT_PATH/../resources/views/welcome.blade.php
          
          


